! python train_regression.py \
    --batch_size 512 \
    --epochs 600 \
    --input_dim 3 \
    --n_hidden_1 128 \
    --n_hidden_2 64 \
    --p_dropout 0.25 \
    --learning_rate 5e-4 \
    --seed 42 \
    --log_steps 5 \
    --data_path "data/train_validate.npz" \
    --output_dir "models/single_task_regression" \
    --log_console