! python train_multitask.py \
    --batch_size 512 \
    --epochs 600 \
    --input_dim 3 \
    --n_hidden_1 128 \
    --n_hidden_2 64 \
    --n_classes 12 \
    --p_dropout 0.25 \
    --learning_rate 1e-3 \
    --seed 42 \
    --log_steps 5 \
    --data_path "data/train_validate.npz" \
    --output_dir "models/multitask_base_LSTM_1e-3lr" 